# Generated by Django 2.1.15 on 2020-05-29 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_auto_20200528_1321'),
        ('home', '0002_filtrele'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparislerim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('siparislerim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.Urunler', verbose_name='Siparislerim')),
            ],
        ),
    ]
