# Generated by Django 2.1.15 on 2020-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='upload_date',
            field=models.DateField(auto_now=True, verbose_name='Eklenme tarihi'),
        ),
    ]
