# Generated by Django 2.1.15 on 2020-05-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_urunler_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.Category', verbose_name='Kategori'),
        ),
    ]
