# Generated by Django 2.1.15 on 2020-05-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_altcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='alt_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='urunler.AltCategory', verbose_name='Kategori'),
            preserve_default=False,
        ),
    ]
