# Generated by Django 2.1.15 on 2020-05-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_urunler_alt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcategory',
            name='ust_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='urunler.Category', verbose_name='Üst kategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='altcategory',
            name='alt_category_name',
            field=models.CharField(max_length=250, verbose_name='Alt Karegori'),
        ),
    ]
