# Generated by Django 2.1.15 on 2020-05-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_auto_20200527_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='seller',
            field=models.CharField(default=1, max_length=250, verbose_name='Satıcı'),
            preserve_default=False,
        ),
    ]
